// Generated by gencpp from file detect_suspicious_person/Camera_msg.msg
// DO NOT EDIT!


#ifndef DETECT_SUSPICIOUS_PERSON_MESSAGE_CAMERA_MSG_H
#define DETECT_SUSPICIOUS_PERSON_MESSAGE_CAMERA_MSG_H

#include <ros/service_traits.h>


#include <detect_suspicious_person/Camera_msgRequest.h>
#include <detect_suspicious_person/Camera_msgResponse.h>


namespace detect_suspicious_person
{

struct Camera_msg
{

typedef Camera_msgRequest Request;
typedef Camera_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Camera_msg
} // namespace detect_suspicious_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detect_suspicious_person::Camera_msg > {
  static const char* value()
  {
    return "2ce4c7abd931d894b27a31926f5f7656";
  }

  static const char* value(const ::detect_suspicious_person::Camera_msg&) { return value(); }
};

template<>
struct DataType< ::detect_suspicious_person::Camera_msg > {
  static const char* value()
  {
    return "detect_suspicious_person/Camera_msg";
  }

  static const char* value(const ::detect_suspicious_person::Camera_msg&) { return value(); }
};


// service_traits::MD5Sum< ::detect_suspicious_person::Camera_msgRequest> should match
// service_traits::MD5Sum< ::detect_suspicious_person::Camera_msg >
template<>
struct MD5Sum< ::detect_suspicious_person::Camera_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detect_suspicious_person::Camera_msg >::value();
  }
  static const char* value(const ::detect_suspicious_person::Camera_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_suspicious_person::Camera_msgRequest> should match
// service_traits::DataType< ::detect_suspicious_person::Camera_msg >
template<>
struct DataType< ::detect_suspicious_person::Camera_msgRequest>
{
  static const char* value()
  {
    return DataType< ::detect_suspicious_person::Camera_msg >::value();
  }
  static const char* value(const ::detect_suspicious_person::Camera_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detect_suspicious_person::Camera_msgResponse> should match
// service_traits::MD5Sum< ::detect_suspicious_person::Camera_msg >
template<>
struct MD5Sum< ::detect_suspicious_person::Camera_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detect_suspicious_person::Camera_msg >::value();
  }
  static const char* value(const ::detect_suspicious_person::Camera_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_suspicious_person::Camera_msgResponse> should match
// service_traits::DataType< ::detect_suspicious_person::Camera_msg >
template<>
struct DataType< ::detect_suspicious_person::Camera_msgResponse>
{
  static const char* value()
  {
    return DataType< ::detect_suspicious_person::Camera_msg >::value();
  }
  static const char* value(const ::detect_suspicious_person::Camera_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECT_SUSPICIOUS_PERSON_MESSAGE_CAMERA_MSG_H
