// Generated by gencpp from file detect_suspicious_person/isMeaning.msg
// DO NOT EDIT!


#ifndef DETECT_SUSPICIOUS_PERSON_MESSAGE_ISMEANING_H
#define DETECT_SUSPICIOUS_PERSON_MESSAGE_ISMEANING_H

#include <ros/service_traits.h>


#include <detect_suspicious_person/isMeaningRequest.h>
#include <detect_suspicious_person/isMeaningResponse.h>


namespace detect_suspicious_person
{

struct isMeaning
{

typedef isMeaningRequest Request;
typedef isMeaningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct isMeaning
} // namespace detect_suspicious_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detect_suspicious_person::isMeaning > {
  static const char* value()
  {
    return "071ff0314258566b4c5235f58f0108cb";
  }

  static const char* value(const ::detect_suspicious_person::isMeaning&) { return value(); }
};

template<>
struct DataType< ::detect_suspicious_person::isMeaning > {
  static const char* value()
  {
    return "detect_suspicious_person/isMeaning";
  }

  static const char* value(const ::detect_suspicious_person::isMeaning&) { return value(); }
};


// service_traits::MD5Sum< ::detect_suspicious_person::isMeaningRequest> should match
// service_traits::MD5Sum< ::detect_suspicious_person::isMeaning >
template<>
struct MD5Sum< ::detect_suspicious_person::isMeaningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detect_suspicious_person::isMeaning >::value();
  }
  static const char* value(const ::detect_suspicious_person::isMeaningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_suspicious_person::isMeaningRequest> should match
// service_traits::DataType< ::detect_suspicious_person::isMeaning >
template<>
struct DataType< ::detect_suspicious_person::isMeaningRequest>
{
  static const char* value()
  {
    return DataType< ::detect_suspicious_person::isMeaning >::value();
  }
  static const char* value(const ::detect_suspicious_person::isMeaningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detect_suspicious_person::isMeaningResponse> should match
// service_traits::MD5Sum< ::detect_suspicious_person::isMeaning >
template<>
struct MD5Sum< ::detect_suspicious_person::isMeaningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detect_suspicious_person::isMeaning >::value();
  }
  static const char* value(const ::detect_suspicious_person::isMeaningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_suspicious_person::isMeaningResponse> should match
// service_traits::DataType< ::detect_suspicious_person::isMeaning >
template<>
struct DataType< ::detect_suspicious_person::isMeaningResponse>
{
  static const char* value()
  {
    return DataType< ::detect_suspicious_person::isMeaning >::value();
  }
  static const char* value(const ::detect_suspicious_person::isMeaningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECT_SUSPICIOUS_PERSON_MESSAGE_ISMEANING_H
