// Generated by gencpp from file detect_suspicious_person/MoveArmResponse.msg
// DO NOT EDIT!


#ifndef DETECT_SUSPICIOUS_PERSON_MESSAGE_MOVEARMRESPONSE_H
#define DETECT_SUSPICIOUS_PERSON_MESSAGE_MOVEARMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_suspicious_person
{
template <class ContainerAllocator>
struct MoveArmResponse_
{
  typedef MoveArmResponse_<ContainerAllocator> Type;

  MoveArmResponse_()
    : res(0)  {
    }
  MoveArmResponse_(const ContainerAllocator& _alloc)
    : res(0)  {
  (void)_alloc;
    }



   typedef int16_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmResponse_

typedef ::detect_suspicious_person::MoveArmResponse_<std::allocator<void> > MoveArmResponse;

typedef boost::shared_ptr< ::detect_suspicious_person::MoveArmResponse > MoveArmResponsePtr;
typedef boost::shared_ptr< ::detect_suspicious_person::MoveArmResponse const> MoveArmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator1> & lhs, const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator1> & lhs, const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detect_suspicious_person

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7db214e1291630e9e4215de89f837d2e";
  }

  static const char* value(const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7db214e1291630e9ULL;
  static const uint64_t static_value2 = 0xe4215de89f837d2eULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_suspicious_person/MoveArmResponse";
  }

  static const char* value(const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 res\n"
;
  }

  static const char* value(const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveArmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_suspicious_person::MoveArmResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<int16_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_SUSPICIOUS_PERSON_MESSAGE_MOVEARMRESPONSE_H
