// Generated by gencpp from file detect_suspicious_person/OdomMoveRequest.msg
// DO NOT EDIT!


#ifndef DETECT_SUSPICIOUS_PERSON_MESSAGE_ODOMMOVEREQUEST_H
#define DETECT_SUSPICIOUS_PERSON_MESSAGE_ODOMMOVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_suspicious_person
{
template <class ContainerAllocator>
struct OdomMoveRequest_
{
  typedef OdomMoveRequest_<ContainerAllocator> Type;

  OdomMoveRequest_()
    : angle(0.0)
    , distance(0.0)
    , direction()  {
    }
  OdomMoveRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)
    , distance(0.0)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;

   typedef double _distance_type;
  _distance_type distance;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OdomMoveRequest_

typedef ::detect_suspicious_person::OdomMoveRequest_<std::allocator<void> > OdomMoveRequest;

typedef boost::shared_ptr< ::detect_suspicious_person::OdomMoveRequest > OdomMoveRequestPtr;
typedef boost::shared_ptr< ::detect_suspicious_person::OdomMoveRequest const> OdomMoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator1> & lhs, const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle &&
    lhs.distance == rhs.distance &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator1> & lhs, const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detect_suspicious_person

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdbd68000e145d32e9331c11df89bc6b";
  }

  static const char* value(const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdbd68000e145d32ULL;
  static const uint64_t static_value2 = 0xe9331c11df89bc6bULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_suspicious_person/OdomMoveRequest";
  }

  static const char* value(const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle   # 回転する角度（単位：ラジアン）\n"
"float64 distance # 前に進む距離\n"
"string direction # 回転する方向（\"left\"または\"right\"）\n"
;
  }

  static const char* value(const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
      stream.next(m.distance);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdomMoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_suspicious_person::OdomMoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_SUSPICIOUS_PERSON_MESSAGE_ODOMMOVEREQUEST_H
