// Generated by gencpp from file detect_suspicious_person/SpeechToText.msg
// DO NOT EDIT!


#ifndef DETECT_SUSPICIOUS_PERSON_MESSAGE_SPEECHTOTEXT_H
#define DETECT_SUSPICIOUS_PERSON_MESSAGE_SPEECHTOTEXT_H

#include <ros/service_traits.h>


#include <detect_suspicious_person/SpeechToTextRequest.h>
#include <detect_suspicious_person/SpeechToTextResponse.h>


namespace detect_suspicious_person
{

struct SpeechToText
{

typedef SpeechToTextRequest Request;
typedef SpeechToTextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeechToText
} // namespace detect_suspicious_person


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detect_suspicious_person::SpeechToText > {
  static const char* value()
  {
    return "d05f0c117cbe0163433dacf612ececb6";
  }

  static const char* value(const ::detect_suspicious_person::SpeechToText&) { return value(); }
};

template<>
struct DataType< ::detect_suspicious_person::SpeechToText > {
  static const char* value()
  {
    return "detect_suspicious_person/SpeechToText";
  }

  static const char* value(const ::detect_suspicious_person::SpeechToText&) { return value(); }
};


// service_traits::MD5Sum< ::detect_suspicious_person::SpeechToTextRequest> should match
// service_traits::MD5Sum< ::detect_suspicious_person::SpeechToText >
template<>
struct MD5Sum< ::detect_suspicious_person::SpeechToTextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detect_suspicious_person::SpeechToText >::value();
  }
  static const char* value(const ::detect_suspicious_person::SpeechToTextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_suspicious_person::SpeechToTextRequest> should match
// service_traits::DataType< ::detect_suspicious_person::SpeechToText >
template<>
struct DataType< ::detect_suspicious_person::SpeechToTextRequest>
{
  static const char* value()
  {
    return DataType< ::detect_suspicious_person::SpeechToText >::value();
  }
  static const char* value(const ::detect_suspicious_person::SpeechToTextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detect_suspicious_person::SpeechToTextResponse> should match
// service_traits::MD5Sum< ::detect_suspicious_person::SpeechToText >
template<>
struct MD5Sum< ::detect_suspicious_person::SpeechToTextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detect_suspicious_person::SpeechToText >::value();
  }
  static const char* value(const ::detect_suspicious_person::SpeechToTextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detect_suspicious_person::SpeechToTextResponse> should match
// service_traits::DataType< ::detect_suspicious_person::SpeechToText >
template<>
struct DataType< ::detect_suspicious_person::SpeechToTextResponse>
{
  static const char* value()
  {
    return DataType< ::detect_suspicious_person::SpeechToText >::value();
  }
  static const char* value(const ::detect_suspicious_person::SpeechToTextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECT_SUSPICIOUS_PERSON_MESSAGE_SPEECHTOTEXT_H
