// Generated by gencpp from file carry_my_luggage/LidarData.msg
// DO NOT EDIT!


#ifndef CARRY_MY_LUGGAGE_MESSAGE_LIDARDATA_H
#define CARRY_MY_LUGGAGE_MESSAGE_LIDARDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carry_my_luggage
{
template <class ContainerAllocator>
struct LidarData_
{
  typedef LidarData_<ContainerAllocator> Type;

  LidarData_()
    : distance()  {
    }
  LidarData_(const ContainerAllocator& _alloc)
    : distance(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::carry_my_luggage::LidarData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carry_my_luggage::LidarData_<ContainerAllocator> const> ConstPtr;

}; // struct LidarData_

typedef ::carry_my_luggage::LidarData_<std::allocator<void> > LidarData;

typedef boost::shared_ptr< ::carry_my_luggage::LidarData > LidarDataPtr;
typedef boost::shared_ptr< ::carry_my_luggage::LidarData const> LidarDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carry_my_luggage::LidarData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carry_my_luggage::LidarData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carry_my_luggage::LidarData_<ContainerAllocator1> & lhs, const ::carry_my_luggage::LidarData_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carry_my_luggage::LidarData_<ContainerAllocator1> & lhs, const ::carry_my_luggage::LidarData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carry_my_luggage

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::carry_my_luggage::LidarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carry_my_luggage::LidarData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carry_my_luggage::LidarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carry_my_luggage::LidarData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carry_my_luggage::LidarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carry_my_luggage::LidarData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carry_my_luggage::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39273b13cbf3e2b5a89f81db86425827";
  }

  static const char* value(const ::carry_my_luggage::LidarData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39273b13cbf3e2b5ULL;
  static const uint64_t static_value2 = 0xa89f81db86425827ULL;
};

template<class ContainerAllocator>
struct DataType< ::carry_my_luggage::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carry_my_luggage/LidarData";
  }

  static const char* value(const ::carry_my_luggage::LidarData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carry_my_luggage::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] distance\n"
;
  }

  static const char* value(const ::carry_my_luggage::LidarData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carry_my_luggage::LidarData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carry_my_luggage::LidarData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carry_my_luggage::LidarData_<ContainerAllocator>& v)
  {
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARRY_MY_LUGGAGE_MESSAGE_LIDARDATA_H
