// Generated by gencpp from file carry_my_luggage/MoveAction.msg
// DO NOT EDIT!


#ifndef CARRY_MY_LUGGAGE_MESSAGE_MOVEACTION_H
#define CARRY_MY_LUGGAGE_MESSAGE_MOVEACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carry_my_luggage
{
template <class ContainerAllocator>
struct MoveAction_
{
  typedef MoveAction_<ContainerAllocator> Type;

  MoveAction_()
    : direction()
    , speed(0.0)
    , time(0.0)
    , distance()  {
    }
  MoveAction_(const ContainerAllocator& _alloc)
    : direction(_alloc)
    , speed(0.0)
    , time(0.0)
    , distance(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _time_type;
  _time_type time;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::carry_my_luggage::MoveAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carry_my_luggage::MoveAction_<ContainerAllocator> const> ConstPtr;

}; // struct MoveAction_

typedef ::carry_my_luggage::MoveAction_<std::allocator<void> > MoveAction;

typedef boost::shared_ptr< ::carry_my_luggage::MoveAction > MoveActionPtr;
typedef boost::shared_ptr< ::carry_my_luggage::MoveAction const> MoveActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carry_my_luggage::MoveAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carry_my_luggage::MoveAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carry_my_luggage::MoveAction_<ContainerAllocator1> & lhs, const ::carry_my_luggage::MoveAction_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.speed == rhs.speed &&
    lhs.time == rhs.time &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carry_my_luggage::MoveAction_<ContainerAllocator1> & lhs, const ::carry_my_luggage::MoveAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carry_my_luggage

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::carry_my_luggage::MoveAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carry_my_luggage::MoveAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carry_my_luggage::MoveAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carry_my_luggage::MoveAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carry_my_luggage::MoveAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carry_my_luggage::MoveAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carry_my_luggage::MoveAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d957ff5f630d6c8c2a1020c896ccaf0";
  }

  static const char* value(const ::carry_my_luggage::MoveAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d957ff5f630d6c8ULL;
  static const uint64_t static_value2 = 0xc2a1020c896ccaf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::carry_my_luggage::MoveAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carry_my_luggage/MoveAction";
  }

  static const char* value(const ::carry_my_luggage::MoveAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carry_my_luggage::MoveAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
"float32 speed\n"
"float32 time\n"
"string distance\n"
;
  }

  static const char* value(const ::carry_my_luggage::MoveAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carry_my_luggage::MoveAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.speed);
      stream.next(m.time);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carry_my_luggage::MoveAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carry_my_luggage::MoveAction_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "distance: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARRY_MY_LUGGAGE_MESSAGE_MOVEACTION_H
