// Generated by gencpp from file find_my_mates/Camera_msgResponse.msg
// DO NOT EDIT!


#ifndef FIND_MY_MATES_MESSAGE_CAMERA_MSGRESPONSE_H
#define FIND_MY_MATES_MESSAGE_CAMERA_MSGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace find_my_mates
{
template <class ContainerAllocator>
struct Camera_msgResponse_
{
  typedef Camera_msgResponse_<ContainerAllocator> Type;

  Camera_msgResponse_()
    : res()  {
    }
  Camera_msgResponse_(const ContainerAllocator& _alloc)
    : res(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Camera_msgResponse_

typedef ::find_my_mates::Camera_msgResponse_<std::allocator<void> > Camera_msgResponse;

typedef boost::shared_ptr< ::find_my_mates::Camera_msgResponse > Camera_msgResponsePtr;
typedef boost::shared_ptr< ::find_my_mates::Camera_msgResponse const> Camera_msgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::find_my_mates::Camera_msgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::find_my_mates::Camera_msgResponse_<ContainerAllocator1> & lhs, const ::find_my_mates::Camera_msgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::find_my_mates::Camera_msgResponse_<ContainerAllocator1> & lhs, const ::find_my_mates::Camera_msgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace find_my_mates

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53af918a2a4a2a182c184142fff49b0c";
  }

  static const char* value(const ::find_my_mates::Camera_msgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53af918a2a4a2a18ULL;
  static const uint64_t static_value2 = 0x2c184142fff49b0cULL;
};

template<class ContainerAllocator>
struct DataType< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "find_my_mates/Camera_msgResponse";
  }

  static const char* value(const ::find_my_mates::Camera_msgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string res\n"
;
  }

  static const char* value(const ::find_my_mates::Camera_msgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Camera_msgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::find_my_mates::Camera_msgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::find_my_mates::Camera_msgResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIND_MY_MATES_MESSAGE_CAMERA_MSGRESPONSE_H
