// Generated by gencpp from file find_my_mates/isMeaning.msg
// DO NOT EDIT!


#ifndef FIND_MY_MATES_MESSAGE_ISMEANING_H
#define FIND_MY_MATES_MESSAGE_ISMEANING_H

#include <ros/service_traits.h>


#include <find_my_mates/isMeaningRequest.h>
#include <find_my_mates/isMeaningResponse.h>


namespace find_my_mates
{

struct isMeaning
{

typedef isMeaningRequest Request;
typedef isMeaningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct isMeaning
} // namespace find_my_mates


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::find_my_mates::isMeaning > {
  static const char* value()
  {
    return "071ff0314258566b4c5235f58f0108cb";
  }

  static const char* value(const ::find_my_mates::isMeaning&) { return value(); }
};

template<>
struct DataType< ::find_my_mates::isMeaning > {
  static const char* value()
  {
    return "find_my_mates/isMeaning";
  }

  static const char* value(const ::find_my_mates::isMeaning&) { return value(); }
};


// service_traits::MD5Sum< ::find_my_mates::isMeaningRequest> should match
// service_traits::MD5Sum< ::find_my_mates::isMeaning >
template<>
struct MD5Sum< ::find_my_mates::isMeaningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::find_my_mates::isMeaning >::value();
  }
  static const char* value(const ::find_my_mates::isMeaningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::find_my_mates::isMeaningRequest> should match
// service_traits::DataType< ::find_my_mates::isMeaning >
template<>
struct DataType< ::find_my_mates::isMeaningRequest>
{
  static const char* value()
  {
    return DataType< ::find_my_mates::isMeaning >::value();
  }
  static const char* value(const ::find_my_mates::isMeaningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::find_my_mates::isMeaningResponse> should match
// service_traits::MD5Sum< ::find_my_mates::isMeaning >
template<>
struct MD5Sum< ::find_my_mates::isMeaningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::find_my_mates::isMeaning >::value();
  }
  static const char* value(const ::find_my_mates::isMeaningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::find_my_mates::isMeaningResponse> should match
// service_traits::DataType< ::find_my_mates::isMeaning >
template<>
struct DataType< ::find_my_mates::isMeaningResponse>
{
  static const char* value()
  {
    return DataType< ::find_my_mates::isMeaning >::value();
  }
  static const char* value(const ::find_my_mates::isMeaningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIND_MY_MATES_MESSAGE_ISMEANING_H
