// Generated by gencpp from file find_my_mates/LidarData.msg
// DO NOT EDIT!


#ifndef FIND_MY_MATES_MESSAGE_LIDARDATA_H
#define FIND_MY_MATES_MESSAGE_LIDARDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace find_my_mates
{
template <class ContainerAllocator>
struct LidarData_
{
  typedef LidarData_<ContainerAllocator> Type;

  LidarData_()
    : distance()
    , front_back()
    , left_right()  {
    }
  LidarData_(const ContainerAllocator& _alloc)
    : distance(_alloc)
    , front_back(_alloc)
    , left_right(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _distance_type;
  _distance_type distance;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _front_back_type;
  _front_back_type front_back;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _left_right_type;
  _left_right_type left_right;





  typedef boost::shared_ptr< ::find_my_mates::LidarData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::find_my_mates::LidarData_<ContainerAllocator> const> ConstPtr;

}; // struct LidarData_

typedef ::find_my_mates::LidarData_<std::allocator<void> > LidarData;

typedef boost::shared_ptr< ::find_my_mates::LidarData > LidarDataPtr;
typedef boost::shared_ptr< ::find_my_mates::LidarData const> LidarDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::find_my_mates::LidarData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::find_my_mates::LidarData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::find_my_mates::LidarData_<ContainerAllocator1> & lhs, const ::find_my_mates::LidarData_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance &&
    lhs.front_back == rhs.front_back &&
    lhs.left_right == rhs.left_right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::find_my_mates::LidarData_<ContainerAllocator1> & lhs, const ::find_my_mates::LidarData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace find_my_mates

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::find_my_mates::LidarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::find_my_mates::LidarData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_my_mates::LidarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_my_mates::LidarData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_my_mates::LidarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_my_mates::LidarData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::find_my_mates::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ace931d02db0ad3fcebb3b540585bf28";
  }

  static const char* value(const ::find_my_mates::LidarData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xace931d02db0ad3fULL;
  static const uint64_t static_value2 = 0xcebb3b540585bf28ULL;
};

template<class ContainerAllocator>
struct DataType< ::find_my_mates::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "find_my_mates/LidarData";
  }

  static const char* value(const ::find_my_mates::LidarData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::find_my_mates::LidarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] distance\n"
"string front_back\n"
"string left_right\n"
;
  }

  static const char* value(const ::find_my_mates::LidarData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::find_my_mates::LidarData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.front_back);
      stream.next(m.left_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LidarData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::find_my_mates::LidarData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::find_my_mates::LidarData_<ContainerAllocator>& v)
  {
    s << indent << "distance[]" << std::endl;
    for (size_t i = 0; i < v.distance.size(); ++i)
    {
      s << indent << "  distance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distance[i]);
    }
    s << indent << "front_back: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.front_back);
    s << indent << "left_right: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.left_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIND_MY_MATES_MESSAGE_LIDARDATA_H
