// Generated by gencpp from file find_my_mates/MoveArm.msg
// DO NOT EDIT!


#ifndef FIND_MY_MATES_MESSAGE_MOVEARM_H
#define FIND_MY_MATES_MESSAGE_MOVEARM_H

#include <ros/service_traits.h>


#include <find_my_mates/MoveArmRequest.h>
#include <find_my_mates/MoveArmResponse.h>


namespace find_my_mates
{

struct MoveArm
{

typedef MoveArmRequest Request;
typedef MoveArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveArm
} // namespace find_my_mates


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::find_my_mates::MoveArm > {
  static const char* value()
  {
    return "b48621f5154048795881ab2e75fbc5f7";
  }

  static const char* value(const ::find_my_mates::MoveArm&) { return value(); }
};

template<>
struct DataType< ::find_my_mates::MoveArm > {
  static const char* value()
  {
    return "find_my_mates/MoveArm";
  }

  static const char* value(const ::find_my_mates::MoveArm&) { return value(); }
};


// service_traits::MD5Sum< ::find_my_mates::MoveArmRequest> should match
// service_traits::MD5Sum< ::find_my_mates::MoveArm >
template<>
struct MD5Sum< ::find_my_mates::MoveArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::find_my_mates::MoveArm >::value();
  }
  static const char* value(const ::find_my_mates::MoveArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::find_my_mates::MoveArmRequest> should match
// service_traits::DataType< ::find_my_mates::MoveArm >
template<>
struct DataType< ::find_my_mates::MoveArmRequest>
{
  static const char* value()
  {
    return DataType< ::find_my_mates::MoveArm >::value();
  }
  static const char* value(const ::find_my_mates::MoveArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::find_my_mates::MoveArmResponse> should match
// service_traits::MD5Sum< ::find_my_mates::MoveArm >
template<>
struct MD5Sum< ::find_my_mates::MoveArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::find_my_mates::MoveArm >::value();
  }
  static const char* value(const ::find_my_mates::MoveArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::find_my_mates::MoveArmResponse> should match
// service_traits::DataType< ::find_my_mates::MoveArm >
template<>
struct DataType< ::find_my_mates::MoveArmResponse>
{
  static const char* value()
  {
    return DataType< ::find_my_mates::MoveArm >::value();
  }
  static const char* value(const ::find_my_mates::MoveArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIND_MY_MATES_MESSAGE_MOVEARM_H
