// Generated by gencpp from file find_my_mates/MoveArmRequest.msg
// DO NOT EDIT!


#ifndef FIND_MY_MATES_MESSAGE_MOVEARMREQUEST_H
#define FIND_MY_MATES_MESSAGE_MOVEARMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace find_my_mates
{
template <class ContainerAllocator>
struct MoveArmRequest_
{
  typedef MoveArmRequest_<ContainerAllocator> Type;

  MoveArmRequest_()
    : x(0)
    , y(0)
    , deg(0)
    , grip(0)  {
    }
  MoveArmRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , deg(0)
    , grip(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _deg_type;
  _deg_type deg;

   typedef int16_t _grip_type;
  _grip_type grip;





  typedef boost::shared_ptr< ::find_my_mates::MoveArmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::find_my_mates::MoveArmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveArmRequest_

typedef ::find_my_mates::MoveArmRequest_<std::allocator<void> > MoveArmRequest;

typedef boost::shared_ptr< ::find_my_mates::MoveArmRequest > MoveArmRequestPtr;
typedef boost::shared_ptr< ::find_my_mates::MoveArmRequest const> MoveArmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::find_my_mates::MoveArmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::find_my_mates::MoveArmRequest_<ContainerAllocator1> & lhs, const ::find_my_mates::MoveArmRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.deg == rhs.deg &&
    lhs.grip == rhs.grip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::find_my_mates::MoveArmRequest_<ContainerAllocator1> & lhs, const ::find_my_mates::MoveArmRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace find_my_mates

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::find_my_mates::MoveArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_my_mates::MoveArmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_my_mates::MoveArmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3783bda1ee9a37e95ff3bedf04675372";
  }

  static const char* value(const ::find_my_mates::MoveArmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3783bda1ee9a37e9ULL;
  static const uint64_t static_value2 = 0x5ff3bedf04675372ULL;
};

template<class ContainerAllocator>
struct DataType< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "find_my_mates/MoveArmRequest";
  }

  static const char* value(const ::find_my_mates::MoveArmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n"
"int16 y\n"
"int16 deg\n"
"int16 grip\n"
;
  }

  static const char* value(const ::find_my_mates::MoveArmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.deg);
      stream.next(m.grip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveArmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::find_my_mates::MoveArmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::find_my_mates::MoveArmRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "deg: ";
    Printer<int16_t>::stream(s, indent + "  ", v.deg);
    s << indent << "grip: ";
    Printer<int16_t>::stream(s, indent + "  ", v.grip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIND_MY_MATES_MESSAGE_MOVEARMREQUEST_H
