// Generated by gencpp from file find_my_mates/SpeechToText.msg
// DO NOT EDIT!


#ifndef FIND_MY_MATES_MESSAGE_SPEECHTOTEXT_H
#define FIND_MY_MATES_MESSAGE_SPEECHTOTEXT_H

#include <ros/service_traits.h>


#include <find_my_mates/SpeechToTextRequest.h>
#include <find_my_mates/SpeechToTextResponse.h>


namespace find_my_mates
{

struct SpeechToText
{

typedef SpeechToTextRequest Request;
typedef SpeechToTextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeechToText
} // namespace find_my_mates


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::find_my_mates::SpeechToText > {
  static const char* value()
  {
    return "d05f0c117cbe0163433dacf612ececb6";
  }

  static const char* value(const ::find_my_mates::SpeechToText&) { return value(); }
};

template<>
struct DataType< ::find_my_mates::SpeechToText > {
  static const char* value()
  {
    return "find_my_mates/SpeechToText";
  }

  static const char* value(const ::find_my_mates::SpeechToText&) { return value(); }
};


// service_traits::MD5Sum< ::find_my_mates::SpeechToTextRequest> should match
// service_traits::MD5Sum< ::find_my_mates::SpeechToText >
template<>
struct MD5Sum< ::find_my_mates::SpeechToTextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::find_my_mates::SpeechToText >::value();
  }
  static const char* value(const ::find_my_mates::SpeechToTextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::find_my_mates::SpeechToTextRequest> should match
// service_traits::DataType< ::find_my_mates::SpeechToText >
template<>
struct DataType< ::find_my_mates::SpeechToTextRequest>
{
  static const char* value()
  {
    return DataType< ::find_my_mates::SpeechToText >::value();
  }
  static const char* value(const ::find_my_mates::SpeechToTextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::find_my_mates::SpeechToTextResponse> should match
// service_traits::MD5Sum< ::find_my_mates::SpeechToText >
template<>
struct MD5Sum< ::find_my_mates::SpeechToTextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::find_my_mates::SpeechToText >::value();
  }
  static const char* value(const ::find_my_mates::SpeechToTextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::find_my_mates::SpeechToTextResponse> should match
// service_traits::DataType< ::find_my_mates::SpeechToText >
template<>
struct DataType< ::find_my_mates::SpeechToTextResponse>
{
  static const char* value()
  {
    return DataType< ::find_my_mates::SpeechToText >::value();
  }
  static const char* value(const ::find_my_mates::SpeechToTextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIND_MY_MATES_MESSAGE_SPEECHTOTEXT_H
